### ISSUE TITLE
Panic in fallback/vanilla.rs

### ISSUE THREAD

**Issue by anorth** [filecoin-project/rust-fil-proofs#1107]
### Description
I logged the following panic in local testing. It's quite likely that this results from a misuse of the API (maybe attempting a proof with zero sectors?), but it probably shouldn't panic, and probably should report what precondition or invariant has been broken.

```
thread '<unnamed>' panicked at 'attempt to calculate the remainder with a divisor of zero', /Users/distiller/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/74db4fd/storage-proofs/post/src/fallback/vanilla.rs:187:24
```

### Acceptance criteria
Instead of panic, return an error describing what went wrong.

**Comment by anorth** [comment]
Backtrace:
```
thread '<unnamed>' panicked at 'attempt to calculate the remainder with a divisor of zero', /Users/distiller/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/74db4fd/storage-proofs/post/src/fallback/vanilla.rs:187:24
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: filecoin_proofs::api::post::generate_winning_post_sector_challenge
  12: filecoin_proofs_api::post::generate_winning_post_sector_challenge
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  14: ffi_toolkit::catch_panic_response
  15: fil_generate_winning_post_sector_challenge
  16: _cgo_66afc6c6cd88_Cfunc_fil_generate_winning_post_sector_challenge
```

**Comment by anorth** [comment]
I can confirm I was calling `fil_generate_winning_post_sector_challenge` with an eligible sector count of zero.
