### ISSUE TITLE
add benchmark for tree building

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#1399]
### Description

I can benchmark building column trees directly from neptune using the `gbench` CLI program. However, performance when actually building column trees (`comm_c`) and regular trees (`comm_r_last`) during precommit 2 is different because the data is read from disk and generally flows through the code paths in `stacked/vanilla/proof.rs`.

I can run that and get timing information from logs by either running a 32 GiB lifecycle test, or by using the `benchy` CLI tool. However, both of these options only generate trees after first replicating an entire sector. For 32 GiB sectors, which is what I want to measure, this takes like two hours — which is not very practical as part of a development cycle when trying to optimize tree building throughput.

Ideally, we would have a way — whether through `benchy` or some other standalone utility — to generate either column trees or regular trees for any sector size (but at least supporting 32 GiB) without first replicating. It's fine to use random data (which must consist of valid `Fr`s), or even all zeroes as input — but the data does have to be on disk and in the expected format.

### Acceptance criteria

I can run a program from the command line and cause it to build either column trees or regular trees (depending on the option provided) for any supported sector size (or at least 32GiB), without a significant delay. This needs to exercise the normal code paths and take input from replica layers written to disk. (If writing the layers to disk is time-consuming, there could be a separate setup command which writes to a specified location once but need not be run every time.)

### Where to begin

https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-porep/src/stacked/vanilla/proof.rs#L371-L399
https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-porep/src/stacked/vanilla/proof.rs#L724-L754
https://github.com/filecoin-project/rust-fil-proofs/blob/master/fil-proofs-tooling/src/bin/benchy/prodbench.rs#L236

**Comment by cryptonemo** [comment]
You can use the window_post bench and after saving the P1 data as @mostcute said, you can run it with with the options to skip P1, C1, C2, so that only P2 is run.  The bench is setup for it, but a slight modification to the main bench file is needed, as right now it groups P1/P2 together.

The slight modification required is here: https://github.com/filecoin-project/rust-fil-proofs/blob/master/fil-proofs-tooling/src/bin/benchy/main.rs#L35

This was commented out because it's destructive to the saved cache if you later want to run other stages alone.

**Comment by porcuquine** [comment]
I tried this and got an error. Since I was using a previously-generated cache, I thought maybe that was the problem, so I reran the whole thing using `--preserve-cache` to create a fresh cache directory. Unfortunately, I got the error again when I tried skipping again.

Do you know what this error means and how I can fix?

It seems like maybe it's generating new (random?) pieces but trying to verify against old (cached) `comm_d`, or something of that nature.

```
FIL_PROOFS_USE_MULTICORE_SDR=1 RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-default-features --features=blst,gpu2 --bin=benchyd window-postp--cache /tmp-fast/cache-32GB-bak --size 32GiB --skip-precommiFIL_PROOFS_USE_MULTICORE_SDR=1 RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-default-features --features=blst,gpu2 --bin=benchyd window-postp--cache /tmp-fast/cache-32GB-bak --size 32GiB --skip-precommitigit push --set-upstream origin changelog-2-6 RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-defa\
ult-features --features=blst,gpu2 --bin=benchy window-post --cache /tmp-fast/cache-32GB-bak --size 32GiB --skip-precommit --s\
kip-commit-phase RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-defa\
ult-features --features=blst,gpu2 --bin=benchy window-post --cache /tmp-fast/cache-32GB-bak --size 32GiB --skip-precommit --s\
kip-commit-phase1RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-defa\
ult-features --features=blst,gpu2 --bin=benchy window-post --cache /tmp-fast/cache-32GB-bak --size 32GiB --skip-precommit --s\
kip-commit-phase➜  fil-proofs-tooling git:(feat/neptune-opencl) ✗ FIL_PROOFS_USE_MULTICORE_SDR=1 RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-default-features --features=blst,gpu2 --bin=benchy window-post --cache /tmp-fast/cache-32GB-bak2 --size 32GiB --skip-commit-phase1 --skip-commit-phase2 --skip-precommit-phase1
warning: unused import: `lazy_static::lazy_static`
 --> storage-proofs-porep/src/stacked/vanilla/proof.rs:1:5
  |
1 | use lazy_static::lazy_static;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::sync::Mutex`
 --> storage-proofs-porep/src/stacked/vanilla/proof.rs:4:5
  |
4 | use std::sync::Mutex;
  |     ^^^^^^^^^^^^^^^^

warning: 2 warnings emitted

    Finished release [optimized] target(s) in 0.50s
     Running `/home/porcuquine/dev/rust-fil-proofs/target/release/benchy window-post --cache /tmp-fast/cache-32GB-bak2 --size 32GiB --skip-commit-phase1 --skip-commit-phase2 --skip-precommit-phase1`
2021-01-22T21:50:51.100 INFO benchy::window_post > Benchy Window PoSt: sector-size=34359738368, api_version=1.0.0, preserve_cache=false, skip_precommit_phase1=false, skip_precommit_phase2=false, skip_commit_phase1=true, skip_commit_phase2=true, test_resume=false
2021-01-22T21:50:51.100 INFO benchy::window_post > Using cache directory "/tmp-fast/cache-32GB-bak2"
2021-01-22T21:50:51.100 INFO benchy::window_post > *** Creating staged file
2021-01-22T21:50:51.100 INFO benchy::window_post > *** Creating sealed file
2021-01-22T21:53:07.611 INFO benchy::window_post > *** Created piece file
2021-01-22T21:55:08.429 INFO filecoin_proofs::api > add_piece:start
2021-01-22T21:56:41.757 INFO filecoin_proofs::api > add_piece:finish
2021-01-22T21:56:41.764 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start: SectorId(0)
2021-01-22T21:57:15.035 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2021-01-22T21:57:15.042 INFO filecoin_proofs::api::seal > verifying pieces
2021-01-22T21:57:15.042 INFO filecoin_proofs::pieces > verifying 1 pieces
thread 'main' panicked at 'failed in seal_pre_commit_phase1: pieces and comm_d do not match', fil-proofs-tooling/src/bin/benchy/window_post.rs:184:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  fil-proofs-tooling git:(feat/neptune-opencl) ✗FIL_PROOFS_USE_MULTICORE_SDR=1 RUST_LOG=info RUSTFLAG="-C target-cpu-=native -g" cargo run --release --no-default-features --features=blst,gpu2 --bin=benchy window-post --cache /tmp-fast/cache-32GB-bak2 --size 32GiB --skip-commit-phase1 --skip-commit-phase2 --skip-precommit-phase1
warning: unused import: `lazy_static::lazy_static`
 --> storage-proofs-porep/src/stacked/vanilla/proof.rs:1:5
  |
1 | use lazy_static::lazy_static;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::sync::Mutex`
 --> storage-proofs-porep/src/stacked/vanilla/proof.rs:4:5
  |
4 | use std::sync::Mutex;
  |     ^^^^^^^^^^^^^^^^

warning: 2 warnings emitted

    Finished release [optimized] target(s) in 0.50s
     Running `/home/porcuquine/dev/rust-fil-proofs/target/release/benchy window-post --cache /tmp-fast/cache-32GB-bak2 --size 32GiB --skip-commit-phase1 --skip-commit-phase2 --skip-precommit-phase1`
2021-01-22T21:50:51.100 INFO benchy::window_post > Benchy Window PoSt: sector-size=34359738368, api_version=1.0.0, preserve_cache=false, skip_precommit_phase1=false, skip_precommit_phase2=false, skip_commit_phase1=true, skip_commit_phase2=true, test_resume=false
2021-01-22T21:50:51.100 INFO benchy::window_post > Using cache directory "/tmp-fast/cache-32GB-bak2"
2021-01-22T21:50:51.100 INFO benchy::window_post > *** Creating staged file
2021-01-22T21:50:51.100 INFO benchy::window_post > *** Creating sealed file
2021-01-22T21:53:07.611 INFO benchy::window_post > *** Created piece file
2021-01-22T21:55:08.429 INFO filecoin_proofs::api > add_piece:start
2021-01-22T21:56:41.757 INFO filecoin_proofs::api > add_piece:finish
2021-01-22T21:56:41.764 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start: SectorId(0)
2021-01-22T21:57:15.035 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2021-01-22T21:57:15.042 INFO filecoin_proofs::api::seal > verifying pieces
2021-01-22T21:57:15.042 INFO filecoin_proofs::pieces > verifying 1 pieces
thread 'main' panicked at 'failed in seal_pre_commit_phase1: pieces and comm_d do not match', fil-proofs-tooling/src/bin/benchy/window_post.rs:184:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  fil-proofs-tooling git:(feat/neptune-opencl) ✗eces > verifying 1 pieces
2021-01-22T21:40:25.747 INFO filecoin_proofs::api::seal > seal_commit_phase1:finish: SectorId(0)
2021-01-22T21:40:25.747 INFO benchy::window_post >
```

**Comment by cryptonemo** [comment]
@porcuquine Can you give this diff a go?

```
diff --git a/fil-proofs-tooling/src/bin/benchy/main.rs b/fil-proofs-tooling/src/bin/benchy/main.rs
index f087db9b..d2e5352b 100644
--- a/fil-proofs-tooling/src/bin/benchy/main.rs
+++ b/fil-proofs-tooling/src/bin/benchy/main.rs
@@ -30,7 +30,6 @@ fn main() -> Result<()> {
                 .help("Preserve the directory where cached files are persisted")
                 .takes_value(false),
         )
-        /*
         .arg(
             Arg::with_name("skip-precommit-phase1")
                 .long("skip-precommit-phase1")
@@ -44,13 +43,6 @@ fn main() -> Result<()> {
                 .required(false)
                 .help("Skip precommit phase 2")
                 .takes_value(false),
-        )*/
-        .arg(
-            Arg::with_name("skip-precommit")
-                .long("skip-precommit")
-                .required(false)
-                .help("Skip precommit phase 1 & 2")
-                .takes_value(false),
         )
         .arg(
             Arg::with_name("skip-commit-phase1")
@@ -191,8 +183,8 @@ fn main() -> Result<()> {
         ("window-post", Some(m)) => {
             let preserve_cache = m.is_present("preserve-cache");
             // For now these options are combined.
-            let skip_precommit_phase1 = m.is_present("skip-precommit");
-            let skip_precommit_phase2 = m.is_present("skip-precommit");
+            let skip_precommit_phase1 = m.is_present("skip-precommit-phase1");
+            let skip_precommit_phase2 = m.is_present("skip-precommit-phase2");
             let skip_commit_phase1 = m.is_present("skip-commit-phase1");
             let skip_commit_phase2 = m.is_present("skip-commit-phase2");
             let test_resume = m.is_present("test-resume");
diff --git a/storage-proofs-porep/src/stacked/vanilla/proof.rs b/storage-proofs-porep/src/stacked/vanilla/proof.rs
index 04f42d07..fc79f7b5 100644
--- a/storage-proofs-porep/src/stacked/vanilla/proof.rs
+++ b/storage-proofs-porep/src/stacked/vanilla/proof.rs
@@ -593,6 +593,14 @@ impl<'a, Tree: 'static + MerkleTreeTrait, G: 'static + Hasher> StackedDrg<'a, Tr
                     assert_eq!(tree_len, config.size.expect("config size failure"));
 
                     // Persist the base and tree data to disk based using the current store config.
+                    let tree_c_store_path = StoreConfig::data_path(&config.path, &config.id);
+                    let tree_c_store_exists = Path::new(&tree_c_store_path).exists();
+                    trace!("tree_c store path {:?} -- exists? {}", tree_c_store_path, tree_c_store_exists);
+                    if tree_c_store_exists {
+                        std::fs::remove_file(&tree_c_store_path)
+                            .expect("failed to remove tree_c_store_path");
+                    }
+
                     let tree_c_store =
                         DiskStore::<<Tree::Hasher as Hasher>::Domain>::new_with_config(
                             tree_len,
```

I can run this like this:

1) Copy over pristine cache dir to `/some/dir`

2) Run: `time RUST_BACKTRACE=full RUST_LOG=trace FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 FIL_PROOFS_USE_GPU_TREE_BUILDER=1 RUSTFLAGS="-C target-cpu=native" cargo run --bin benchy -- window-post --size 2KiB --skip-precommit-phase1 --skip-commit-phase1 --skip-commit-phase2 --cache /some/dir`

**Comment by porcuquine** [comment]
Thanks, @cryptonemo. This worked for me. Is this code safe to commit, or just good as a local hack?

**Comment by cryptonemo** [comment]
> Thanks, @cryptonemo. This worked for me. Is this code safe to commit, or just good as a local hack?

It's 'safe', but can cause some option matrix issues.  If all of the stages are broken up like this, it's possible to have broken behaviour depending on what combination is used (e.g. just using  `--skip-precommit-phase2` will cause other stages to be broken on a given run.  That was the trade off when just lumping them (PC1/PC2) together. Just an effort to try to minimize breakage from end-users.

Given that trade off, I could make a PR for this where the user just needs to think about what they're doing a bit in order to not have broken runs.  Since it's useful in this context, I don't see a reason it shouldn't be allowed somehow.

**Comment by porcuquine** [comment]
That sounds good. I will use as-is for my purposes but not commit anything.

I think your PR sounds like a good idea. Can you include documentation (maybe in README?), perhaps with some canonical and known-good examples to help users get this right in the future — especially later, when we've all forgotten how it works again?

**Comment by porcuquine** [comment]
Any chance this happened? Would be helpful for me right now if so.

**Comment by vmx** [comment]
It's currently not on my radar, but it could be next week (or on the radar of someone else?)

**Comment by cryptonemo** [comment]
Yes, on my radar, but for now use the patch similar to shown.
