### ISSUE TITLE
Rust panic while working at Precommit1

### ISSUE THREAD

**Issue by ZyanWlayor** [filecoin-project/rust-fil-proofs#1449]
### Description
**My lotusworker run into a mistake randomly with following logs:**

2021-04-21T22:33:21.776 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-04-21T22:33:21.776 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner

thread '<unnamed>thread '<unnamed>thread '' panicked at 'thread '<unnamed>thread 'range end index 18089479344 out of range for slice of length 17179869184thread '<unnamed>thread '' panicked at 'thread '<unnamed>' panicked at '', <unnamed>' panicked at '<unnamed>range end index 18089479344 out of range for slice of length 17179869184<unnamed>' panicked at 'range end index 25025297232 out of range for slice of length 17179869184' panicked at 'range end index 18089479344 out of range for slice of length 17179869184' panicked at '', ' panicked at 'range end index 25025297232 out of range for slice of length 17179869184', range end index 25025297232 out of range for slice of length 17179869184', range end index 18089479344 out of range for slice of length 17179869184range end index 25025297232 out of range for slice of length 17179869184', ', ', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:::112::::112112112:112112112112:::18::::181818
18181818

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'range end index 18089479344 out of range for slice of length 17179869184range end index 25025297232 out of range for slice of length 17179869184', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs::112112::1818

thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'range end index 25025297232 out of range for slice of length 17179869184range end index 18089479344 out of range for slice of length 17179869184', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs::112112::1818

thread '<unnamed>' panicked at 'range end index 18089479344 out of range for slice of length 17179869184', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:112:18
thread '<unnamed>' panicked at 'range end index 25025297232 out of range for slice of length 17179869184', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:112:18

**My machine have a AMD EPYC 7542 32-Core Processor,1TB ECC RAM and a  NVIDIA GeForce RTX 2080 Ti**

**Comment by cryptonemo** [comment]
The log appears to be very strange and unlike anything I've observed.  The same layers are attempted to be generated and written repeatedly?  Does this happen with single core SDR?  What version (or commit hash) of proofs is this?

**Comment by ZyanWlayor** [comment]
@cryptonemo my version of proofs is release v5.4.0 and my task num set to 7 while I have 1TB RAM.Could it be a problem of insufficient memory?

**Comment by cryptonemo** [comment]
No, I don't think it could be a problem due to insufficient RAM, unless RAM is being used as the primary layer storage.  The error could be accessing data on disk (make sure there is no shortage of space).  I've never seen layers re-writing like that, I don't see how that is happening.  No code was modified?  Just need to rule that out.

Can you get logs using `RUST_LOG=trace`?

**Comment by ZyanWlayor** [comment]
Tested,after i reduce the number of worker nums to 6, this problem disappered,tks. @cryptonemo

**Comment by cryptonemo** [comment]
Thank you for following up!
