### ISSUE TITLE
Rust panic "out of range for slice"on precommit1

### ISSUE THREAD

**Issue by moran666666** [filecoin-project/rust-fil-proofs#1459]
### Description
2021-05-12T01:36:51.041 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
2021-05-12T01:36:51.041 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start: SectorId(13384)
2021-05-12T01:37:57.460 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2021-05-12T01:42:00.332 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2021-05-12T01:42:26.014 INFO filecoin_proofs::api::seal > verifying pieces
2021-05-12T01:42:26.014 INFO filecoin_proofs::pieces > verifying 1 pieces
2021-05-12T01:42:26.016 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase1
2021-05-12T01:42:26.018 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[2048 / 2147483648]
2021-05-12T01:42:26.018 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opening /nvme/filecoin-proof-parameters/v28-sdr-parent-4905486b7af19558ac3649bc6261411858b6add534438878c4ee3b29d8b9de0b.cache, verify enabled: false
2021-05-12T01:42:26.019 INFO storage_proofs_porep::stacked::vanilla::proof > multi core replication
2021-05-12T01:42:26.019 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > create labels
2021-05-12T01:42:26.163 INFO storage_proofs_porep::stacked::vanilla::memory_handling > initializing cache
2021-05-12T01:42:26.164 WARN storage_proofs_porep::stacked::vanilla::memory_handling > failed to lock map Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }, falling back
2021-05-12T01:42:26.170 WARN storage_proofs_porep::stacked::vanilla::memory_handling > failed to lock map Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }, falling back
2021-05-12T01:42:26.170 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 1
2021-05-12T01:42:26.170 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 1
2021-05-12T01:42:26.171 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-05-12T01:42:42.360 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 4 store with id layer-4
2021-05-12T01:42:42.360 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 5
2021-05-12T01:42:42.360 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 5
2021-05-12T01:42:42.360 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
thread '<unnamed>' panicked at 'range end index 24719253240 out of range for slice of length 17179869184', /home/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-6.1.0/src/stacked/vanilla/create_label/multi.rs:116:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-05-12T01:52:45.856 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2021-05-12T01:53:29.432 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 3 store with id layer-3
2021-05-12T01:53:29.432 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 4
2021-05-12T01:53:29.432 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 4
2021-05-12T01:53:29.432 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-05-12T01:53:49.530 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2021-05-12T01:54:21.152 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 11 store with id layer-11
2021-05-12T01:54:28.577 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish: SectorId(13241)
2021-05-12T01:54:28.579 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2021-05-12T01:56:02.435 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2021-05-12T01:56:33.909 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 7 store with id layer-7
2021-05-12T01:56:33.909 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 8
2021-05-12T01:56:33.909 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 8
2021-05-12T01:56:33.909 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-05-12T01:59:55.019+0800	DEBUG	advmgr	sector-storage/worker_local.go:129	acquired sector {{475305 13393} 9} (e:1; a:0): {{0 0} /nvme/.lotusstorage/unsealed/s-t0475305-13393  }
2021-05-12T01:59:55.027+0800	DEBUG	advmgr	sector-storage/worker_local.go:129	acquired sector {{475305 13393} 9} (e:1; a:6): {{0 0} /nvme/.lotusstorage/unsealed/s-t0475305-13393 /nvme/.lotusstorage/sealed/s-t0475305-13393 /nvme/.lotusstorage/cache/s-t0475305-13393}
2021-05-12T01:59:55.029 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
2021-05-12T01:59:55.030 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start: SectorId(13393)
thread '<unnamed>' panicked at 'range end index 23279453336 out of range for slice of length 17179869184', /home/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-6.1.0/src/stacked/vanilla/create_label/multi.rs:352:30
2021-05-12T02:01:04.036 INFO filecoin_proofs::api::seal > building merkle tree for the original data
thread '<unnamed>' panicked at 'range end index 24719253240 out of range for slice of length 17179869184', /home/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-6.1.0/src/stacked/vanilla/create_label/multi.rs:116:18

**My machine have a AMD EPYC 7302 16-Core Processor,1TB ECC RAM and a NVIDIA GeForce RTX 2080 Ti , run 6 precommit1**

**Comment by cryptonemo** [comment]
Please include `RUST_LOG=trace` debugging and make sure that there is enough disk space available.

**Comment by cryptonemo** [comment]
Is this possibly related? https://github.com/filecoin-project/rust-fil-proofs/issues/1449

**Comment by moran666666** [comment]
I run 2 workers do the p1 jobs on a machine, echo woker run 6 p1.

**Comment by moran666666** [comment]
> Is this possibly related? #1449

Yes, but I didn't solve it.

**Comment by moran666666** [comment]
> Please include `RUST_LOG=trace` debugging and make sure that there is enough disk space available.

Disk space available is enough.

**Comment by mathshero** [comment]
It happened on our environment, too. With enough RAM and disk space.

**Comment by vmx** [comment]
Is this still a problem, if yes, feel free to re-open this issue or create a new one.
