### ISSUE TITLE
[BUG] failed to get gpu lock: PoisonError { .. }

### ISSUE THREAD

**Issue by firesWu** [filecoin-project/rust-fil-proofs#1478]
### Description

when pc2 panic once, it will get gpu lock failed all the time until we restart worker.
when we build tree panic,   _gpu_lock is not release, so we can not get lock next time.

first error:
```
thread '<unnamed>' panicked at 'from_repr failure: NotInField("0xfb1bf5d3a97d013282397714ecd4fbad17256b288b0e23ea54a9b0dd658529c1")', /root/lotus_compiler/mainnet/rust-fil-proofs/filecoin-hashers/src/poseidon.rs:398:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/result.rs:1355:5
   3: storage_proofs_porep::encode::encode
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   5: rayon::iter::plumbing::Folder::consume_iter
   6: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: std::panicking::try
   9: rayon_core::registry::in_worker
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: rayon_core::job::StackJob<L,F,R>::run_inline
  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
```

multi error:
```
thread '<unnamed>' panicked at 'failed to get gpu lock: PoisonError { .. }', /root/lotus_compiler/mainnet/rust-fil-proofs/storage-proofs-porep/src/stacked/vanilla/proof.rs:591:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/result.rs:1355:5
   3: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   4: std::panicking::try
   5: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
   6: rayon_core::registry::WorkerThread::wait_until_cold
   7: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'failed to receive base_data, tree_data for tree_c: RecvError', /root/lotus_compiler/mainnet/ns_rust-fil-proofs/storage-proofs-porep/src/stacked/vanilla/proof.rs:643:26
stack backtrace:
   0: rust_begin_unwind
```

**Comment by cryptonemo** [comment]
Possibly related to #1476?  More logging is required.  In that case, an OpenCl error (out of memory) causes future GPU usage to fail like this.  We need to find out why your GPU ran out of RAM.

**Comment by firesWu** [comment]
@cryptonemo   my point is even tree build panic, gpu_lock still need release.   so that pc2 could finish in next retry.

**Comment by cryptonemo** [comment]
Currently, the GPU lock cannot be released when the GPU state is hung.  Preventing that state in the first place is ideal.

**Comment by Jasonwu123** [comment]
Hi guys , I had the same error. How can I resolve it , thanks?

**Comment by firesWu** [comment]
> Hi guys , I had the same error. How can I resolve it , thanks?

I just comment gpu_lock, it is unnecessary for me.

**Comment by cryptonemo** [comment]
Possible solution worth looking into? https://github.com/filecoin-project/lotus/issues/6980#issuecomment-892743688

**Comment by vmx** [comment]
The locking code has changed since then, hence I'm closing this issue. If there's still a problem, please open a new issue.
