### ISSUE TITLE
64GB Lifecycle Test Failure

### ISSUE THREAD

**Issue by shawnrader** [filecoin-project/rust-fil-proofs#1647]
During  64gb lifecycle test, a failure was encountered during the verify seal operation.  This test ran after the recent dependency updates of bellperson and ec-gpu-gen, and this specific failure was not observed previously.
This is the assert which failed:
https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/tests/api.rs#L1547

Failing test case: 
https://github.com/filecoin-project/proofs-buildbot/actions/runs/3490176199/jobs/5866444223#step:17:26666

Besides the assert there appears to be no other errors in the test log.
Last 100 lines of test log:
```
2022-11-19T18:06:36.908 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T18:06:36.908 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T18:06:36.908 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T18:06:36.908 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T18:49:45.189 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1115 times
2022-11-19T18:49:45.189 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T18:50:13.802 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 5 store with id layer-5
2022-11-19T18:50:13.802 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 6
2022-11-19T18:50:13.802 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 6
2022-11-19T18:50:13.802 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T18:50:13.803 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T18:50:13.803 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T18:50:13.803 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T18:50:13.803 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T18:50:13.803 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T19:33:37.682 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1591 times
2022-11-19T19:33:37.682 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T19:34:15.988 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 6 store with id layer-6
2022-11-19T19:34:15.988 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 7
2022-11-19T19:34:15.988 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 7
2022-11-19T19:34:15.988 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T19:34:15.988 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T19:34:15.988 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T19:34:15.989 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T19:34:15.989 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T19:34:15.989 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T20:16:55.643 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 759 times
2022-11-19T20:16:55.643 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T20:17:26.233 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 7 store with id layer-7
2022-11-19T20:17:26.233 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 8
2022-11-19T20:17:26.233 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 8
2022-11-19T20:17:26.233 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T20:17:26.233 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T20:17:26.233 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T20:17:26.234 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T20:17:26.234 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T20:17:26.234 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:00:48.270 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1713 times
2022-11-19T21:00:48.270 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T21:01:28.123 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 8 store with id layer-8
2022-11-19T21:01:28.123 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 9
2022-11-19T21:01:28.123 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 9
2022-11-19T21:01:28.124 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T21:01:28.124 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:01:28.124 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T21:01:28.124 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:01:28.124 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T21:01:28.124 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:44:56.017 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1684 times
2022-11-19T21:44:56.017 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 9 store with id layer-9
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 10
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 10
2022-11-19T21:45:37.508 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:45:37.508 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T21:45:37.508 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T21:45:37.508 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T22:28:51.697 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1154 times
2022-11-19T22:28:51.698 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T22:29:33.828 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 10 store with id layer-10
2022-11-19T22:29:33.828 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 11
2022-11-19T22:29:33.828 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 11
2022-11-19T22:29:33.829 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 0
2022-11-19T22:29:33.829 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 2
2022-11-19T22:29:33.829 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T22:29:33.829 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T22:29:33.829 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > binding core in producer thread 1
2022-11-19T22:29:33.829 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2022-11-19T23:12:51.707 DEBUG storage_proofs_porep::stacked::vanilla::create_label::multi > PRODUCER NOT READY: 1271 times
2022-11-19T23:12:51.707 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2022-11-19T23:13:30.582 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 11 store with id layer-11
2022-11-19T23:19:43.651 TRACE filecoin_proofs::api > unseal_range_inner:finish
2022-11-19T23:19:43.651 INFO filecoin_proofs::api > unseal_range:finish
2022-11-19T23:19:48.286 TRACE filecoin_proofs::api::seal > compute_comm_d:start
2022-11-19T23:19:48.286 TRACE filecoin_proofs::pieces > verifying 1 pieces
2022-11-19T23:19:48.286 TRACE filecoin_proofs::api::seal > compute_comm_d:finish
2022-11-19T23:19:48.286 INFO filecoin_proofs::api::seal > verify_seal:start: SectorId(9259733836259213201)
2022-11-19T23:19:48.286 INFO filecoin_proofs::caches > trying parameters memory cache for: STACKED[68719476736]-verifying-key
2022-11-19T23:19:48.286 INFO filecoin_proofs::caches > found params in memory cache for STACKED[68719476736]-verifying-key
2022-11-19T23:19:48.286 TRACE filecoin_proofs::api::seal > got verifying key (68719476736) while verifying seal
2022-11-19T23:19:48.295 INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(9259733836259213201)
thread 'test_seal_lifecycle_64gib_porep_id_v1_1_top_8_8_2_api_v1_1' panicked at 'failed to verify valid seal', filecoin-proofs/tests/api.rs:1547:5
stack backtrace:
   0: std::panicking::begin_panic
   1: api::proof_and_unseal
   2: api::create_seal
   3: api::seal_lifecycle
   4: core::ops::function::FnOnce::call_once
   5: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_seal_lifecycle_64gib_porep_id_v1_1_top_8_8_2_api_v1_1 ... FAILED

failures:

failures:
    test_seal_lifecycle_64gib_porep_id_v1_1_top_8_8_2_api_v1_1

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 45 filtered out; finished in 63759.47s
```

**Comment by shawnrader** [comment]
Re-ran the test over the weekend and it failed on the same case.  I enabled the RUST_BACKTRACE=full but did not get a more detailed stack.  May need to disable optimizations or add additional tracing to the test.

**Comment by shawnrader** [comment]
Added some additional tracing and 64-gb test appears to be failing in verify_proofs_batch in Bellperson.  Adding some additional tracing to Bellperson and re-running test.

**Comment by shawnrader** [comment]
I attempted running the 64-gig test with GPU acceleration disabled (cuda=0, opencl=0) and the test passed successfully.  This issue appears isolated to GPU acceleration.  Test run: https://github.com/filecoin-project/proofs-buildbot/actions/runs/3879527102/jobs/6616794083

**Comment by vmx** [comment]
This was fixed with https://github.com/filecoin-project/ec-gpu/pull/44!
